---
title: "lecture 1 presentation"
author: "Simon"
date: "29/7/2022"
output:
  beamer_presentation:
    toc: yes
    slide_level: 2
    theme: AnnArbor
    colortheme: dolphin
    fonttheme: structurebold
---

# Intro til kursus: 

### mig 

- Jeg tog videregående makro kurset sidste år. 

- Mail: sfth18@student.aau.dk

- kontor: fibigerstræde 10, lokale 24. 

### kurset

- 2 lektioner af 4 timer hvor største delen bliver brugt på øvelser. 

- Gennemgang af løsning de sidse 30 minutter. (også på moodle)


# Differentierings regler (funktioner af en variable)

For differentiable funktioner $f(x)$, $g(x)$. $h(x)$ og konstanten $a$ gælder: 

$$f(x)=a,  \rightarrow f'(x) = 0$$
$$f(x)=ag(x)  \rightarrow f'(x) = ag'(x)$$
$$f(x)=g(x) + h(x)  \rightarrow f'(x) = g'(x) + h'(x)$$
$$f(x)=g(x)  h(x)  \rightarrow f'(x) = g'(x)h(x) + g(x)h'(x)$$
$$f(x)= \frac{g(x)}{h(x)}  \rightarrow f'(x) = \frac{g'(x)h(x) - g(x)h(x)} {(h(x))^2}$$
$$f(x)=x^a  \rightarrow f'(x) = ax^{a-1}$$
$$f(x)=g(x)^a  \rightarrow f'(x) = ag(x)^{a-1}g'(x)$$
$$f(x)=e^x  \rightarrow f'(x) = e^x$$
$$f(x)=ln(x)  \rightarrow f'(x) = \frac{1}{x}$$

## Eksempel på Eksamens opgave sidste år: 



Find an expression for the impact of a marginal change in g on the fraction of output
that is saved on the balanced growth path. Can one tell whether this expression is
positive or negative? 

- Andel af output opsparet i steady state: 

$$s= \frac{f(k^*)-c^*}{f(k^*)}$$
- Vi ved også at $\dot{k}=0$ i steady state, derfor kan vi skrive  $\dot{k}= f(k) - c - (n+g)k$ som følgene: 

$$f(k^*) - c^* = (n+g)k^*$$

## Eksempel på Eksamens opgave sidste år: 


- Derfor kan vi nu omskrive andelen af savings til 

$$s= \frac{(n+g)k^*}{f(k^*)}$$

- Vi skal nu differentiere dette udtryk mhs. til $g$. (hint: brug regler for differeniering af en brøk. Og husk $g$ har også en effekt på $k^*$ derfor skal kædereglen også bruges)

- 15 minuter (svaret er på næste side)


## Eksempel på Eksamens opgave sidste år: 

$$\frac {\delta s} {\delta g} = \frac {f(k^*)[(n+g)(\frac{\delta k^*}{\delta g})+k^*] - (n+g)k^* f'(k^*)(\frac{\delta k^*}{\delta g})}{[f(k^*)]^2}$$

- Vi kan nu gange $f(k^*)$ ind i parentesen og sætter $(n+g)(\frac{\delta k^*} {\delta g})$ udenfor


$$\frac {\delta s} {\delta g} = \frac {f(k^*)(n+g)(\frac{\delta k^*}{\delta g})+ f(k^*) k^* - (n+g)k^* f'(k^*)(\frac{\delta k^*}{\delta g})}{[f(k^*)]^2}$$


$$\frac {\delta s} {\delta g} = \frac {(n+g)[f(k^*) -k^* f'(k^*)](\frac{\delta k^*} {\delta g}) + f(k^*)k^*} {[f(k^*)]^2}$$

- Da vi er i steady state ved vi at $f'(k^*)= \rho + \theta g$ vi kan differentiere med $g$ på begge sider af lighedstegnet. (5 minutter, igen svaret er på næste slide)


## Eksempel på Eksamens opgave sidste år: 


$$f''(k^*)(\frac{\delta k^*} {\delta g}) = \theta$$

- Hvis vi isolere $(\frac{\delta k^*} {\delta g})$: 

$$(\frac{\delta k^*} {\delta g}) = \frac{\theta}{f''(k^*)}$$

- Vi kan substituere dette ind i udtrykket: 

$$\frac {\delta s} {\delta g} = \frac {(n+g)[f(k^*) -k^* f'(k^*)](\frac{\theta} {f''(k^*)}) + f(k^*)k^*} {[f(k^*)]^2}$$

## Eksempel på Eksamens opgave sidste år: 


- Vi kan nu gange med $f''(k^*)$ over og under brøken. 

$$\frac{\delta s}{\delta g} = \frac{(n+g)[f(k^*)-k^*f'(k^*)]\theta + f(k^*)k^*f''(k^*)}{[f(k^*)]^2 f''(k^*)}$$

- Hvad kan vi sige om effekten af en marginal ændring i g på savings af output?

  - Vi ved at der er aftagende marginal produkt på kapital. 


# Kædereglen - Sammensatte funktioner

- Lad $z= f(x,y)$
- Lad $y$ og $x$ være funktioner af t: $y= g(t)$ og $x= h(t)$
- Her er $z$ en sammensat funktion af $t$: $z= f(g(t),h(t))$

- Brug **kædereglen**:

$$\frac{dz}{dt} = \frac{\delta z}{\delta x} * \frac{\delta x}{\delta t} + \frac{\delta z}{\delta y} * \frac{\delta y}{\delta t}$$




## Kædereglen Eksempel

Antag funktionen: $F(x.y) = ln(x) + y^2$, hvor $x= e^{10t}$ og $y= \sqrt{50t}$

- Step 1: Find $F_x'(x,y)$ og $F_y'(x,y)$

$$F_x'(x,y) = \frac{1}{x}$$
$$F_y'(x,y) = 2y$$

- Step 2: Find $x_t'$ og $y_t'$

$$x_t' = 10e^{10t}$$
$$y_t' = \frac {50}{2\sqrt{50t}}$$ (Brug kæderegl for 1 variable)

## Kædereglen Eksempel

- Step 3: Brug nu funktionen for kædereglen

$$F_t'(x,y)=\frac{1}{x}10^{10t} + 2y \frac{50}{2\sqrt{50t}}$$
$$F_t'(x,y)=\frac{1}{x}10^{10t} + y\frac{50}{\sqrt{50t}}$$

# Differensiering med sidebetingler (Langrange)

## Simpelt eksempel

Funktion $f(x,y)=x+y$ med betingelsen  $g(x,y)= x^2 +y =1$

Vi ønsker at optimere (find max) af f(x,y) givet side betingelsen derfor opstil Langrange:

$$L= x+y - \lambda(x^2 + y -1)$$
Find afledte:

$$L'_x = 1- 2x\lambda$$
$$L'_y = 1 - \lambda$$
$$L'_\lambda = -x^2 - y + 1$$

Vi kan nu sætte disse ligmed 0 og løse for de tre ubekendte. 

Vi opnår følgende løsning: $x = 1/2$, $y= 3/4$ og $\lambda = 1$.

## Optimeringm af nytte funktion med budgetrestriktion (OLG model) 

Antag budget restriktionen:  $C_{1,t} + \frac{1}{(1+r_{t+1})} * C_{2,t+1}= W_t*A_t$

Samt nytte funktionen: $U_t = U(C_{1,t}) + \beta U(C_{2.t+1})$

- Hvor $\beta = 1/(1+\rho)$

Antag at: $U(C_{j,t})= ln(C_{j,t})$

Dermed opstil Langrange: 

$$L= ln(C_{1,t} + \frac{1}{1+\rho}*ln(C_{2,t+1}) - \lambda((C_{1,t} + \frac{1}{1+\rho}*C_{2,t+1}) - W_t*A_t) $$


## Optimeringm af nytte funktion med budgetrestriktion (OLG model)

Find afledte, og sæt ligmed 0: 

$$L'_{C_{1,t}} = 1/C_{1,t} - \lambda=0$$
$$L'_{C_{2,t+1}} = \frac{1}{1+\rho} * \frac{1}{C_{2,t+1}} - \frac{\lambda}{1+r_{t+1}}=0$$

Vi kan isolere $\lambda = 1/C_{1,t}$ og indsætte i $L'_{C_{2,t+1}}$

Vi kan nu reducere til vi har: 

$$\frac{C_{1,t}}{C_{2,t+1}} = \frac{1+\rho}{1+r_{t+1}}$$
(også kaldt Euler equation)
