---
title: "Opgaver lektion 2"
author: "Simon"
date: "4/8/2022"
output:
  pdf_document: default
  html_document: default
---

# Opgaver til fase diagrammer?

# Opgave 2.7 b og c fra bogen:

Describe how each of the following affects the $\dot{c} =0$, and $\dot{k} = 0$ curves in figure 2.5 and thus how they affect the balanced growth path values of $c$ and $k$.

## b
 A downward shift in the production function

## c 

A change in the rate of depreciation from the value zero assumed in the text to some positive level. 




# Opgave 1



Find Taylor approximation af:

- (a.) $f(x) = 4x^3 + 2x^2 -3x +2$ når $x=0$ 

- (b.) $f(x) = e^{3x}$ når $x=0$

- (b.) $f(x) = \sqrt{1+x}$ når $x=0$

- (b.) $f(x) = \sqrt[3]{x}$ når $x=1$

- (b.) $F(K) = AK^\alpha$ når $K=1$

- (b.) $f(x) = 5(ln(1-x)- \sqrt{1-x})$ når $x=0$


# Opgave 2

Givet funktionen $f(x)=x^6 - x^3$ hvad er koefficienten for ledet $(x+2)^4$ i Taylor approximation af f(x) omkring $x=-2$

# Opgave 3 

Find en 1. order Taylor approximation omkring $k=k^*$ når du ved at udviklingen i kapital over tid følger følgende ligning: 


$$\dot{k} = s*f(k) - (n+g+\delta)k$$

# Opgave 4:

Bogen opgave 1.13

Go through steps analogous to those in equation (1.29)-(1.32) to find how quickly $y$ converges to $y^*$ in the vicinity of the balanced growth path 
(hint:; since $y=f(k)$, we can write $k=g(y)$ where $g(.) = f^{-1}(.)$)


# Opgave 5: 

**Opgave 2.8 fra bogen:**

Derive an expression analogous to eq 2.40 for the case of a positive depreciation


## Løsning opgave 3

$$\dot{k} = s*f(k) - (n+g+\delta)k$$

$$\dot{k}(k)$$

- Vi ønsker at lave en første ordens taylor approximation omkring $k=k^*$

- Så hvor vi før havde $c$ har vi nu $k^*$

$$\dot{k} \approx \frac{\delta \dot{k}(k)}{\delta k}|_{k=k^*} (k-k^*)$$

Antag:

$$\lambda = -(\frac{\delta \dot{k}(k)}{\delta k})$$
Dermed:

$$\dot{k} \approx - \lambda|_{k=k^*} (k-k^*)$$

Hvis $k>k^*$ ved vi at $\dot{k} < 0$.
Omvendt hvis $k<k^*$ ved vi at $\dot{k} > 0$.
Dermed ved vi at hældning $(\frac{\delta \dot{k}(k)}{\delta k})$ er negativ

$$\dot{k} \approx  \lambda|_{k=k^*} (k-k^*)$$

Vi vil nu finde $\lambda= - (\frac{\delta \dot{k}(k)}{\delta k})$:

$$-(\dot{k} \approx  \lambda|_{k=k^*}) = -[s* f'(k^*) - (n + g + \delta)]$$

$$= (n+g+\delta) - s*f(k)$$

For at opnå et steady state niveau. ønsker vi at $\dot{k}=0$ Derfor $S= (n+g+\delta)k^*$

$$= (n+g+\delta) - \frac{(n+g+\delta)* k^* * f'(k^*)}{f(k^*)}$$

Vi ved $s=S/f(k^*)$

Derudover ved vi at kapital andelen kan skrives som følgende $\alpha_k= \frac{k^* (f'(k))}{f(k^*)}$ 

$$\lambda = [1-\alpha_k] (n+ g+ \delta)$$



